---
title: "Demand_Forcasting"
author: "Jon Peters"
date: "10/30/2020"
output: html_document
---

```{r}
library(tidyverse)
library(caret)
library(forecast)
train <- read_csv("train.csv")
test <- read_csv("test.csv")
numStores <- unique(train$store)
numItems <- unique(train$item)

numStores <- unique(train$store)
numItems <- unique(train$item)

# Visualize any trends we have in out data by store
ggplot(train, mapping = aes(x=date, y=sales, color = as.factor(store))) + geom_point() + theme_classic()
```

Find any missing values.

```{r}
summary(train)
#No missing values!


```
## Time Series
Using an arima function to predict for each indovidual store and item.

```{r}
for (i in numStores){
    for (j in numItems){
        temp_df <- data.frame()
        t <- Arima((train %>% filter(store == i, item == j))$sales, order = c(0, 2, 2), seasonal = c(0, 0, 0))
        
        f <- Arima((test %>% filter(store == i, item == j))$date, model = t)
        
        temp_df <- cbind(Id = (test %>% filter(store == i, item == j))$id, x = as.data.frame(as.double(f$fitted)))
        
        finalDF <- rbind(finalDF, temp_df)
    }
}
colnames(finalDF) <- c("Id", "sales")

write_csv(finalDF, "submission.csv")
```
## Feature Engineering

```{r}
train <- train %>% mutate(dayOfWeek = weekdays(date),
                          year = lubridate::year(date), 
                          month = lubridate::month(date),
                          day = lubridate::day(date)) %>% select(-date)

test <- test %>% mutate(dayOfWeek = weekdays(date),
                        year = lubridate::year(date),
                        month = lubridate::month(date),
                        day = lubridate::day(date)) %>% select(-date)
```

## Model Fitting

```{r}
finalDF <- data.frame()

tune.grid <- expand.grid(n.trees = seq(1, 300, 10),
                         interaction.depth = seq(1, 5, 1),
                         n.minobsinnode = c(9, 10, 11),
                         shrinkage = .1)


for (i in numStores){
    
    #for (j in numItems){
        temp_df <- data.frame()
        
        linreg <- train(form=sales~., 
                data=(train %>% filter(store == i) %>% select(-store)),
                method = "gbm",
                tuneGrid =tune.grid,
                trControl=trainControl(method="repeatedcv",
                                       number=5,
                                       repeats = 3),
                verbose = FALSE
                )
        
        
        temp_df <- data.frame(Id= (test %>% filter(store == i) %>% select(id)), sales = predict(linreg, newdata = test %>% filter(store == i) %>% select(-id)))

        finalDF <- rbind(finalDF, temp_df)
    #}
}
colnames(finalDF) <- c("Id", "sales")

linreg$bestTune

write_csv(finalDF, "submission.csv")

finalDF
```

